--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.105.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06/03/2025 11:50:47 AM
-- Server version: 8.0.41
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO gms.alert_log(id, alert_date, last_alert_date) VALUES
(2, '2025-03-03', '2025-03-03 11:29:01'),
(3, '2025-03-04', '2025-03-04 08:04:38'),
(4, '2025-03-05', '2025-03-05 08:07:30'),
(5, '2025-03-06', '2025-03-06 09:10:34');


INSERT INTO gms.clients(client_id, name, phone_number, subscription_status, subscription_end_date, created_at, package_id) VALUES
('1', 'Ali Osseili', '+961 76 313174', 'active', '2025-06-04', '2025-03-03 08:56:47', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('81d29b8bba190529928c5166e441efad', 'John Doe', '3254361', 'active', '2026-03-06', '2025-03-05 08:40:03', '4ba8ee26-f990-11ef-9dcc-cc28aa53b74d'),
('b46650b6f25f70010602a2f3939726e3', 'Client 6', '68735148', 'active', '2025-05-03', '2025-03-04 10:12:45', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('d1bdfef96381437ae629f7aae009fc2a', 'xdfxdf', '45485', 'inactive', NULL, '2025-03-04 13:02:10', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('ff1e89f3dd169e3a57040903c51ea385', 'Client 7', '98463516', 'active', '2025-05-03', '2025-03-04 11:05:00', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d');



INSERT INTO gms.packages(id, name, price, number_of_days) VALUES
('ee6fae48-f842-11ef-aeee-cc28aa53b74d', 'Starter Package', 150.00, 30),
('4ba8ee26-f990-11ef-9dcc-cc28aa53b74d', 'Yearly Plan', 2000.00, 365);


INSERT INTO gms.payments(payment_id, client_id, amount, payment_method, payment_date, payment_status, package_id) VALUES
('67c5d00c164dc', '0', 150.00, 'cash', '2025-03-03 16:51:40', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6a63fc145a', '0', 150.00, 'cash', '2025-03-04 08:05:35', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6baadafcb4', '0', 150.00, 'cash', '2025-03-04 09:32:45', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6bf3df3925', '0', 150.00, 'cash', '2025-03-04 09:52:14', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6bfe97d779', '0', 150.00, 'cash', '2025-03-04 09:55:05', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6c13294296', '0', 150.00, 'cash', '2025-03-04 10:00:34', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6c3644fa60', '6e013dacafecbf8c4a0f57bef2ab6f87', 150.00, 'cash', '2025-03-04 10:09:56', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6c40d1dfe6', 'b46650b6f25f70010602a2f3939726e3', 150.00, 'cash', '2025-03-04 10:12:45', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6cf1e1cb87', '1', 150.00, 'cash', '2025-03-04 10:59:58', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6d04c6c2e7', 'ff1e89f3dd169e3a57040903c51ea385', 150.00, 'cash', '2025-03-04 11:05:00', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6d7137b2a9', 'b46650b6f25f70010602a2f3939726e3', 150.00, 'cash', '2025-03-04 11:33:55', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6ebc2eed7a', 'd1bdfef96381437ae629f7aae009fc2a', 150.00, 'cash', '2025-03-04 13:02:10', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6ebe748c9d', 'ff1e89f3dd169e3a57040903c51ea385', 150.00, 'cash', '2025-03-04 13:02:47', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c71a54d0da7', 'b255f43f4b6281fc381870d88487951d', 150.00, 'cash', '2025-03-04 16:20:52', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c7fa7c5815b', 'b255f43f4b6281fc381870d88487951d', 150.00, 'cash', '2025-03-05 08:17:16', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c7fab933c20', 'b46650b6f25f70010602a2f3939726e3', 150.00, 'cash', '2025-03-05 08:18:17', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c7fac3d7456', 'ff1e89f3dd169e3a57040903c51ea385', 150.00, 'cash', '2025-03-05 08:18:27', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c7ffd3142e1', '81d29b8bba190529928c5166e441efad', 500.00, 'cash', '2025-03-05 08:40:03', 'Completed', '4ba8ee26-f990-11ef-9dcc-cc28aa53b74d');


INSERT INTO gms.products(product_id, name, description, price, quantity_in_stock, created_at) VALUES
(3, 'Vshape Protein', 'Whey protein ', 100.00, 173, '2025-03-05 10:44:47'),
(5, 'Creatine', 'Vshape Creatine', 50.00, 90, '2025-03-05 13:39:04'),
(6, '5904233620163', 'Cotex Tissue Box', 2.00, 9993, '2025-03-06 11:15:27'),
(7, '9501101373655', 'Bactigel Handgel', 1.20, 997, '2025-03-06 11:37:07');


INSERT INTO gms.sale_items(sale_item_id, sale_id, product_id, quantity, price) VALUES
(1, 1, 3, 2, 100.00),
(2, 2, 3, 1, 100.00),
(3, 3, 3, 0, 100.00),
(4, 5, 3, 0, 100.00),
(5, 5, 5, 0, 50.00),
(6, 6, 3, 3, 100.00),
(7, 7, 3, 3, 100.00),
(8, 7, 5, 1, 50.00),
(9, 8, 5, 2, 50.00),
(10, 8, 3, 4, 100.00),
(11, 9, 5, 11, 50.00),
(12, 10, 5, 100, 50.00),
(13, 11, 5, 1, 50.00),
(14, 11, 3, 2, 100.00),
(15, 12, 3, 1, 100.00),
(16, 13, 5, 99, 50.00),
(17, 14, 5, 3, 50.00),
(18, 15, 5, 1, 50.00),
(19, 15, 3, 1, 100.00),
(20, 16, 3, 1, 100.00),
(21, 17, 5, 1, 50.00),
(22, 18, 5, 1, 50.00),
(23, 18, 3, 4, 100.00),
(24, 19, 5, 1, 50.00),
(25, 20, 5, 2, 50.00),
(26, 20, 3, 1, 100.00),
(27, 21, 5, 1, 50.00),
(28, 21, 3, 2, 100.00),
(29, 22, 3, 2, 100.00),
(30, 23, 6, 3, 2.00),
(31, 24, 7, 2, 1.20),
(32, 24, 6, 3, 2.00),
(33, 25, 6, 1, 2.00),
(34, 25, 7, 1, 1.20);


INSERT INTO gms.sales(sale_id, user_id, total_amount, sale_date) VALUES
(1, 7, 200.00, '2025-03-05 11:59:56'),
(2, 7, 100.00, '2025-03-05 13:03:14'),
(3, 7, 0.00, '2025-03-05 14:29:38'),
(4, 7, 0.00, '2025-03-05 14:29:40'),
(5, 7, 0.00, '2025-03-05 14:32:14'),
(6, 7, 300.00, '2025-03-05 14:40:47'),
(7, 7, 350.00, '2025-03-05 14:49:52'),
(8, 7, 500.00, '2025-03-05 14:50:50'),
(9, 7, 550.00, '2025-03-05 14:51:35'),
(10, 7, 5000.00, '2025-03-05 14:52:25'),
(11, 7, 250.00, '2025-03-05 14:58:13'),
(12, 7, 100.00, '2025-03-05 15:04:41'),
(13, 7, 4950.00, '2025-03-05 15:13:45'),
(14, 7, 150.00, '2025-03-05 15:50:42'),
(15, 7, 150.00, '2025-03-05 15:56:46'),
(16, 7, 100.00, '2025-03-05 16:00:13'),
(17, 7, 50.00, '2025-03-05 16:03:22'),
(18, 7, 450.00, '2025-03-05 16:13:41'),
(19, 7, 50.00, '2025-03-05 16:16:57'),
(20, 7, 200.00, '2025-03-05 16:47:42'),
(21, 7, 250.00, '2025-03-06 09:28:54'),
(22, 7, 200.00, '2025-03-06 10:22:42'),
(23, 7, 6.00, '2025-03-06 11:28:36'),
(24, 7, 8.40, '2025-03-06 11:37:44'),
(25, 7, 3.20, '2025-03-06 11:44:19');


INSERT INTO gms.users(id, useremail, username, password, token, created_at, isadmin, canadd, canedit, candelete, phone_number) VALUES
(7, 'henry@gmail.com', 'ali', '$2y$10$vC41AOMLc.nfBlZFOwukkuN/44tpQIlIjnGdRMMOVdlzOTf5fT5zq', '754bcf4b23f6b6f887e30182f22ac0b7bd577256d26e7e744546ac8403ee855a3aa236909dd98571731913e85f8dd1b1e7c9', '2020-09-24 17:53:37', 1, 1, 1, 1, NULL),
(11, 'ali@gmail.com', 'alioss', '$2y$10$83pATx.M9lbHYJl7eMgUROFpFh8iT78cXvchFAOwm8j0ky0ypijAC', 'e3f8fe5f5d6236dce4dbce6aed0586d37b803d33da855047a06154a82f27bcdf98137d74a414adf3aa660fa6c33f010be0fa', '2024-11-25 10:39:58', 0, 1, 1, 1, '+961 76313174'),
(12, 'test@email.com', 'alijamil', '$2y$10$JZ1Qg.jWSD.xPjfhF5diA.R0lvArJ5eVwyBGFkOcADl86jgVPFN1i', '83e0c5819c815e507c0690ef07b8fdccc412a5a7eb2abfbdb8123b6adc252649ad4ff05f9cb67fb150834088190a5128273f', '2024-12-30 11:21:20', 0, 1, 1, 1, NULL),
(13, 'testtest@test.test', 'test', '$2y$10$/NWzf5L6SzQZ8lyn/d8B8OLe0XuBagvnNYw4Jziyf2eu4dMNnTWt2', '35448c560e5a1a12d9708c2fb25d31cd30c8cf7d92cd6df5e3f3f8785bff85eec602abac6f08f81ff3ba6fc3fd674c2ef4b0', '2025-01-07 13:44:01', 0, 1, 1, 1, NULL),
(14, 'customer.service@webmail-cd.com', 'zeina', '$2y$10$kttt1sAls4t0D86krcMhouJGFvBRVmfs2vZbQEQ0d3.Hdhgvarh8K', 'ea950df6934355aff819c59e2374887010b7f15a88133995fb3cadf229846095e6b3577338fbf1bf452b419142be1b02f5de', '2025-02-04 08:20:55', 0, 1, 1, 1, '+243 904444111'),
(15, 'import2@webmail-cd.com', 'Fatima', '$2y$10$Y2G8DNDACvCmLYz1NH6H1OP5Por5K0i7lSVj.QKPKDWDqTKiyr8k6', '7a152f4f336b13bd1b0c179796f7ca953bbe501a9264b09d6f99fd2c53229b8d354bb2b9d00514316b323218cf2ef3eceb0a', '2025-02-04 08:23:09', 0, 1, 1, 1, '+243 900232323'),
(16, 'import6@webmail-cd.com', 'rayane', '$2y$10$WM9CaEYbIBuZy1Syv.9kfu13l6Oz8MgNL20l7ipsjDKB2cPk9bN9G', 'f9249ab27dddc56a251b3d2147a30e287cf23a573078b65a0fac9464d25b2f6c1ce60c6510d597943b0455cc8540522915cf', '2025-02-04 08:23:56', 0, 1, 1, 1, '+243 811023076'),
(17, 'import@webmail-cd.com', 'Zaynab', '$2y$10$SHxh441kI1J5qGGku416R.ZZxTmIevN0VQO2YpTAyeg2Uzs943nou', '9ecafb8091f069bebe85f23fdf13a1af57500807b864d141bff030f2773ddec4b2deb608cf82c3fd6232577655dc35e13f82', '2025-02-04 08:24:52', 0, 1, 1, 1, '+243 828300586'),
(18, 'import4@webmail-cd.com', 'Sleiman', '$2y$10$QvQAqNTRnCH5FpeaI8rHGu5BNnq6yxutPkAQMr0XbipE4X1KtMZ5u', '57049f9005aab867851955f922888d5f0599019e2429aa074cef97701a2242eff68759bc572eae9086be8836719d863621fd', '2025-02-04 08:26:01', 0, 1, 1, 1, '+243 832135341'),
(19, 'import7@webmail-cd.com', 'Anjie', '$2y$10$0hWum/Fk2fm.y2Em2mfqO.vF30ASKlmaBRQwe0meqyoK2XQKevs7W', 'fcc16e0aee0204846ee6ccaba3d23dd3674baabf41a68a9244a26246093847990048848171cf62e42c117fc5f62cfaa146ac', '2025-02-04 08:27:16', 0, 1, 1, 1, '+243 900033888'),
(20, 'frankbula8@gmail.com', 'frank', '$2y$10$dIcFk/fT5gp8OLugaGQoI.EUPr7Yk4Gl7l/2iO7EqF0iS0/YblX6C', 'c91017dbef3361f7d72fdedf2fc01910656577a5de56906700baf11e06294faa6c7cec142c48d28fefd6240612b65106374f', '2025-02-04 08:27:49', 0, 1, 1, 1, '+243 904074200'),
(21, 'logistic@chemaf.net', 'ibrahim', '$2y$10$J//sTS.UvfVkVwm6Sxmly.3Rglxf3PIDiPQQTCJdqCJddve5vYLQG', 'bcd6af01f579b8c5a05898db35b0b33cfd34da9f1d25d22f36a34e87e3d565f639cb666597112e84f1aeee9d7a28c26a8dad', '2025-02-04 13:19:19', 0, 1, 1, 1, '+243 903537750'),
(22, 'afrifood@webmail-cd.com', 'Hoteit', '$2y$10$kYmo0qdP9mqZVpulQkfaNuQ8YJrS8VYeUcK1QC2Aw0YNB5s.Ak7Eq', '2b82306f4477b63a97e6b43eea16339fc7ce66933b601363a65b5964ea49d5281e4fdb0160462d31f160d239e73409258d32', '2025-02-11 14:41:19', 0, 1, 1, 1, '+243 831 470 744');