--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.105.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 24/03/2025 4:26:45 PM
-- Server version: 8.0.41
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE flexigym;

--
-- Drop table `inventory_transactions`
--
DROP TABLE IF EXISTS inventory_transactions;

--
-- Drop table `sale_items`
--
DROP TABLE IF EXISTS sale_items;

--
-- Drop table `inventory_items`
--
DROP TABLE IF EXISTS inventory_items;

--
-- Drop table `role_permissions`
--
DROP TABLE IF EXISTS role_permissions;

--
-- Drop table `permissions`
--
DROP TABLE IF EXISTS permissions;

--
-- Drop table `subscription_payments`
--
DROP TABLE IF EXISTS subscription_payments;

--
-- Drop procedure `sp_delete_package`
--
DROP PROCEDURE IF EXISTS sp_delete_package;

--
-- Drop procedure `sp_get_packages_with_subscriptions_count`
--
DROP PROCEDURE IF EXISTS sp_get_packages_with_subscriptions_count;

--
-- Drop table `subscriptions`
--
DROP TABLE IF EXISTS subscriptions;

--
-- Drop procedure `sp_create_package`
--
DROP PROCEDURE IF EXISTS sp_create_package;

--
-- Drop procedure `sp_get_all_packages`
--
DROP PROCEDURE IF EXISTS sp_get_all_packages;

--
-- Drop procedure `sp_get_package_by_id`
--
DROP PROCEDURE IF EXISTS sp_get_package_by_id;

--
-- Drop procedure `sp_get_popular_packages`
--
DROP PROCEDURE IF EXISTS sp_get_popular_packages;

--
-- Drop procedure `sp_update_package`
--
DROP PROCEDURE IF EXISTS sp_update_package;

--
-- Drop table `packages`
--
DROP TABLE IF EXISTS packages;

--
-- Drop table `subscribers`
--
DROP TABLE IF EXISTS subscribers;

--
-- Drop table `sales`
--
DROP TABLE IF EXISTS sales;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `roles`
--
DROP TABLE IF EXISTS roles;

--
-- Set default database
--
USE flexigym;

--
-- Create table `roles`
--
CREATE TABLE roles (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  description text DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `name` on table `roles`
--
ALTER TABLE roles
ADD UNIQUE INDEX name (name);

--
-- Create table `users`
--
CREATE TABLE users (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  email varchar(100) NOT NULL,
  password varchar(255) NOT NULL,
  role_id int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `email` on table `users`
--
ALTER TABLE users
ADD UNIQUE INDEX email (email);

--
-- Create foreign key
--
ALTER TABLE users
ADD CONSTRAINT users_ibfk_1 FOREIGN KEY (role_id)
REFERENCES roles (id) ON DELETE SET NULL;

--
-- Create table `sales`
--
CREATE TABLE sales (
  id int NOT NULL AUTO_INCREMENT,
  subtotal decimal(10, 2) NOT NULL,
  tax decimal(10, 2) NOT NULL,
  discount decimal(10, 2) DEFAULT 0.00,
  total decimal(10, 2) NOT NULL,
  payment_method enum ('cash', 'card') NOT NULL,
  customer_id int DEFAULT NULL,
  customer_name varchar(100) DEFAULT NULL,
  customer_email varchar(100) DEFAULT NULL,
  created_by int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE sales
ADD CONSTRAINT sales_ibfk_1 FOREIGN KEY (created_by)
REFERENCES users (id) ON DELETE SET NULL;

--
-- Create table `subscribers`
--
CREATE TABLE subscribers (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  email varchar(255) DEFAULT NULL,
  phone varchar(20) DEFAULT NULL,
  address text DEFAULT NULL,
  date_of_birth date DEFAULT NULL,
  gender enum ('male', 'female', 'other') DEFAULT NULL,
  emergency_contact varchar(255) DEFAULT NULL,
  emergency_phone varchar(20) DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `email` on table `subscribers`
--
ALTER TABLE subscribers
ADD UNIQUE INDEX email (email);

--
-- Create table `packages`
--
CREATE TABLE packages (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  description text DEFAULT NULL,
  days int NOT NULL,
  price decimal(10, 2) NOT NULL,
  features json DEFAULT NULL,
  is_popular tinyint(1) DEFAULT 0,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 14,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_update_package`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_update_package (IN p_id int,
IN p_name varchar(100),
IN p_description text,
IN p_days int,
IN p_price decimal(10, 2),
IN p_features json,
IN p_is_popular boolean)
BEGIN
  UPDATE packages
  SET name = p_name,
      description = p_description,
      days = p_days,
      price = p_price,
      features = p_features,
      is_popular = p_is_popular,
      updated_at = CURRENT_TIMESTAMP
  WHERE id = p_id;

  -- Return 1 if the row was updated, 0 otherwise
  SELECT
    ROW_COUNT() AS updated_rows;
END
$$

--
-- Create procedure `sp_get_popular_packages`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_popular_packages ()
BEGIN
  SELECT
    id,
    name,
    description,
    days,
    price,
    features,
    is_popular,
    created_at,
    updated_at
  FROM packages
  WHERE is_popular = 1
  ORDER BY price ASC;
END
$$

--
-- Create procedure `sp_get_package_by_id`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_package_by_id (IN p_id int)
BEGIN
  SELECT
    id,
    name,
    description,
    days,
    price,
    features,
    is_popular,
    created_at,
    updated_at
  FROM packages
  WHERE id = p_id;
END
$$

--
-- Create procedure `sp_get_all_packages`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_all_packages ()
BEGIN
  SELECT
    id,
    name,
    description,
    days,
    price,
    features,
    is_popular,
    created_at,
    updated_at
  FROM packages
  ORDER BY price ASC;
END
$$

--
-- Create procedure `sp_create_package`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_package (IN p_name varchar(100),
IN p_description text,
IN p_days int,
IN p_price decimal(10, 2),
IN p_features json,
IN p_is_popular boolean)
BEGIN
  INSERT INTO packages (name,
  description,
  days,
  price,
  features,
  is_popular)
    VALUES (p_name, p_description, p_days, p_price, p_features, p_is_popular);

  -- Return the newly created package
  SELECT
    LAST_INSERT_ID() AS id;
END
$$

DELIMITER ;

--
-- Create table `subscriptions`
--
CREATE TABLE subscriptions (
  id int NOT NULL AUTO_INCREMENT,
  subscriber_id int NOT NULL,
  package_id int NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status enum ('active', 'expired', 'cancelled', 'pending') NOT NULL DEFAULT 'pending',
  payment_status enum ('paid', 'pending', 'failed') NOT NULL DEFAULT 'pending',
  total_amount decimal(10, 2) NOT NULL,
  amount_paid decimal(10, 2) DEFAULT 0.00,
  payment_method enum ('cash', 'card', 'bank_transfer') DEFAULT NULL,
  notes text DEFAULT NULL,
  created_by int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE subscriptions
ADD CONSTRAINT subscriptions_ibfk_1 FOREIGN KEY (subscriber_id)
REFERENCES subscribers (id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE subscriptions
ADD CONSTRAINT subscriptions_ibfk_2 FOREIGN KEY (package_id)
REFERENCES packages (id);

--
-- Create foreign key
--
ALTER TABLE subscriptions
ADD CONSTRAINT subscriptions_ibfk_3 FOREIGN KEY (created_by)
REFERENCES users (id);

DELIMITER $$

--
-- Create procedure `sp_get_packages_with_subscriptions_count`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_get_packages_with_subscriptions_count ()
BEGIN
  SELECT
    p.id,
    p.name,
    p.description,
    p.days,
    p.price,
    p.features,
    p.is_popular,
    COUNT(s.id) AS active_subscriptions,
    p.created_at,
    p.updated_at
  FROM packages p
    LEFT JOIN subscriptions s
      ON p.id = s.package_id
      AND s.status = 'active'
  GROUP BY p.id
  ORDER BY active_subscriptions DESC, p.name ASC;
END
$$

--
-- Create procedure `sp_delete_package`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_delete_package (IN p_id int)
BEGIN
  -- First check if the package has any subscriptions
  DECLARE subscription_count int;

  SELECT
    COUNT(*) INTO subscription_count
  FROM subscriptions
  WHERE package_id = p_id;

  -- Only delete if there are no subscriptions
  IF subscription_count = 0 THEN
    DELETE
      FROM packages
    WHERE id = p_id;
    SELECT
      ROW_COUNT() AS deleted_rows;
  ELSE
    -- Return 0 to indicate no rows were deleted
    SELECT
      0 AS deleted_rows,
      'Package has subscriptions and cannot be deleted' AS message;
  END IF;
END
$$

DELIMITER ;

--
-- Create table `subscription_payments`
--
CREATE TABLE subscription_payments (
  id int NOT NULL AUTO_INCREMENT,
  subscription_id int NOT NULL,
  amount decimal(10, 2) NOT NULL,
  payment_date date NOT NULL,
  payment_method enum ('cash', 'card', 'bank_transfer') NOT NULL,
  transaction_id varchar(255) DEFAULT NULL,
  notes text DEFAULT NULL,
  created_by int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE subscription_payments
ADD CONSTRAINT subscription_payments_ibfk_1 FOREIGN KEY (subscription_id)
REFERENCES subscriptions (id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE subscription_payments
ADD CONSTRAINT subscription_payments_ibfk_2 FOREIGN KEY (created_by)
REFERENCES users (id);

--
-- Create table `permissions`
--
CREATE TABLE permissions (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  description text DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `name` on table `permissions`
--
ALTER TABLE permissions
ADD UNIQUE INDEX name (name);

--
-- Create table `role_permissions`
--
CREATE TABLE role_permissions (
  role_id int NOT NULL,
  permission_id int NOT NULL,
  PRIMARY KEY (role_id, permission_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE role_permissions
ADD CONSTRAINT role_permissions_ibfk_1 FOREIGN KEY (role_id)
REFERENCES roles (id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE role_permissions
ADD CONSTRAINT role_permissions_ibfk_2 FOREIGN KEY (permission_id)
REFERENCES permissions (id) ON DELETE CASCADE;

--
-- Create table `inventory_items`
--
CREATE TABLE inventory_items (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  description text DEFAULT NULL,
  sku varchar(50) NOT NULL,
  barcode varchar(100) DEFAULT NULL,
  quantity int NOT NULL DEFAULT 0,
  price decimal(10, 2) NOT NULL,
  cost decimal(10, 2) NOT NULL,
  category varchar(50) DEFAULT NULL,
  image_src text DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `sku` on table `inventory_items`
--
ALTER TABLE inventory_items
ADD UNIQUE INDEX sku (sku);

--
-- Create table `sale_items`
--
CREATE TABLE sale_items (
  id int NOT NULL AUTO_INCREMENT,
  sale_id int NOT NULL,
  item_id int NOT NULL,
  quantity int NOT NULL,
  price decimal(10, 2) NOT NULL,
  total decimal(10, 2) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE sale_items
ADD CONSTRAINT sale_items_ibfk_1 FOREIGN KEY (sale_id)
REFERENCES sales (id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE sale_items
ADD CONSTRAINT sale_items_ibfk_2 FOREIGN KEY (item_id)
REFERENCES inventory_items (id);

--
-- Create table `inventory_transactions`
--
CREATE TABLE inventory_transactions (
  id int NOT NULL AUTO_INCREMENT,
  item_id int NOT NULL,
  type enum ('purchase', 'sale', 'adjustment_in', 'adjustment_out', 'beginning') NOT NULL,
  quantity int NOT NULL,
  price decimal(10, 2) DEFAULT NULL,
  total_amount decimal(10, 2) NOT NULL,
  notes text DEFAULT NULL,
  customer_supplier varchar(100) DEFAULT NULL,
  payment_status varchar(50) DEFAULT NULL,
  created_by int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 14,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE inventory_transactions
ADD CONSTRAINT inventory_transactions_ibfk_1 FOREIGN KEY (item_id)
REFERENCES inventory_items (id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE inventory_transactions
ADD CONSTRAINT inventory_transactions_ibfk_2 FOREIGN KEY (created_by)
REFERENCES users (id) ON DELETE SET NULL;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;