--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.105.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06/03/2025 12:13:58 PM
-- Server version: 8.0.41
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE gms;

--
-- Drop table `alert_log`
--
DROP TABLE IF EXISTS alert_log;

--
-- Drop table `packages`
--
DROP TABLE IF EXISTS packages;

--
-- Drop table `payments`
--
DROP TABLE IF EXISTS payments;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop event `update_subscription_status`
--
DROP EVENT IF EXISTS update_subscription_status;

--
-- Drop table `clients`
--
DROP TABLE IF EXISTS clients;

--
-- Drop table `inventory_transactions`
--
DROP TABLE IF EXISTS inventory_transactions;

--
-- Drop table `sale_items`
--
DROP TABLE IF EXISTS sale_items;

--
-- Drop table `products`
--
DROP TABLE IF EXISTS products;

--
-- Drop table `sales`
--
DROP TABLE IF EXISTS sales;

--
-- Set default database
--
USE gms;

--
-- Create table `sales`
--
CREATE TABLE sales (
  sale_id int NOT NULL AUTO_INCREMENT,
  user_id int DEFAULT NULL,
  total_amount decimal(10, 2) DEFAULT NULL,
  sale_date timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (sale_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 26,
AVG_ROW_LENGTH = 655,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `user_id` on table `sales`
--
ALTER TABLE sales
ADD INDEX user_id (user_id);

--
-- Create table `products`
--
CREATE TABLE products (
  product_id int NOT NULL AUTO_INCREMENT,
  name varchar(100) DEFAULT NULL,
  description text DEFAULT NULL,
  price decimal(10, 2) DEFAULT NULL,
  quantity_in_stock int DEFAULT NULL,
  created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (product_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `sale_items`
--
CREATE TABLE sale_items (
  sale_item_id int NOT NULL AUTO_INCREMENT,
  sale_id int DEFAULT NULL,
  product_id int DEFAULT NULL,
  quantity int DEFAULT NULL,
  price decimal(10, 2) DEFAULT NULL,
  PRIMARY KEY (sale_item_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 35,
AVG_ROW_LENGTH = 481,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE sale_items
ADD CONSTRAINT sale_items_ibfk_1 FOREIGN KEY (sale_id)
REFERENCES sales (sale_id);

--
-- Create foreign key
--
ALTER TABLE sale_items
ADD CONSTRAINT sale_items_ibfk_2 FOREIGN KEY (product_id)
REFERENCES products (product_id);

--
-- Create table `inventory_transactions`
--
CREATE TABLE inventory_transactions (
  transaction_id int NOT NULL AUTO_INCREMENT,
  product_id int DEFAULT NULL,
  quantity int DEFAULT NULL,
  transaction_type enum ('sale', 'restock') DEFAULT NULL,
  transaction_date timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (transaction_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create foreign key
--
ALTER TABLE inventory_transactions
ADD CONSTRAINT inventory_transactions_ibfk_1 FOREIGN KEY (product_id)
REFERENCES products (product_id);

--
-- Create table `clients`
--
CREATE TABLE clients (
  client_id varchar(36) NOT NULL,
  name varchar(100) NOT NULL,
  phone_number varchar(20) NOT NULL,
  subscription_status enum ('active', 'inactive', 'expired') DEFAULT 'inactive',
  subscription_end_date date DEFAULT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  package_id varchar(36) NOT NULL,
  PRIMARY KEY (client_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `phone_number` on table `clients`
--
ALTER TABLE clients
ADD UNIQUE INDEX phone_number (phone_number);

DELIMITER $$

--
-- Create event `update_subscription_status`
--
CREATE 
	DEFINER = 'root'@'localhost'
EVENT update_subscription_status
	ON SCHEDULE EVERY '1' DAY
	STARTS '2025-03-03 12:00:00'
	DO 
UPDATE gms.clients
  SET subscription_status = 'expired'
  WHERE subscription_end_date < CURDATE()
  AND subscription_status != 'expired'
$$

ALTER 
	DEFINER = 'root'@'localhost'
EVENT update_subscription_status
	ENABLE
$$

DELIMITER ;

--
-- Create table `users`
--
CREATE TABLE users (
  id int NOT NULL AUTO_INCREMENT,
  useremail varchar(255) NOT NULL,
  username varchar(50) NOT NULL,
  password varchar(255) NOT NULL,
  token varchar(255) DEFAULT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  isadmin tinyint(1) DEFAULT 0,
  canadd tinyint(1) NOT NULL DEFAULT 0,
  canedit tinyint(1) NOT NULL DEFAULT 0,
  candelete tinyint(1) NOT NULL DEFAULT 0,
  phone_number varchar(32) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 23,
AVG_ROW_LENGTH = 1260,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `useremail` on table `users`
--
ALTER TABLE users
ADD UNIQUE INDEX useremail (useremail);

--
-- Create table `payments`
--
CREATE TABLE payments (
  payment_id varchar(36) NOT NULL,
  client_id varchar(36) DEFAULT NULL,
  amount decimal(10, 2) DEFAULT NULL,
  payment_method enum ('cash') DEFAULT 'cash',
  payment_date timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  payment_status enum ('Pending', 'Completed', 'Refunded') DEFAULT 'Pending',
  package_id varchar(36) NOT NULL,
  PRIMARY KEY (payment_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1024,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `packages`
--
CREATE TABLE packages (
  id varchar(36) NOT NULL,
  name varchar(50) NOT NULL,
  price decimal(19, 2) NOT NULL,
  number_of_days int NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `alert_log`
--
CREATE TABLE alert_log (
  id int NOT NULL AUTO_INCREMENT,
  alert_date date NOT NULL,
  last_alert_date timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table sales
--
INSERT INTO sales VALUES
(1, 7, 200.00, '2025-03-05 11:59:56'),
(2, 7, 100.00, '2025-03-05 13:03:14'),
(3, 7, 0.00, '2025-03-05 14:29:38'),
(4, 7, 0.00, '2025-03-05 14:29:40'),
(5, 7, 0.00, '2025-03-05 14:32:14'),
(6, 7, 300.00, '2025-03-05 14:40:47'),
(7, 7, 350.00, '2025-03-05 14:49:52'),
(8, 7, 500.00, '2025-03-05 14:50:50'),
(9, 7, 550.00, '2025-03-05 14:51:35'),
(10, 7, 5000.00, '2025-03-05 14:52:25'),
(11, 7, 250.00, '2025-03-05 14:58:13'),
(12, 7, 100.00, '2025-03-05 15:04:41'),
(13, 7, 4950.00, '2025-03-05 15:13:45'),
(14, 7, 150.00, '2025-03-05 15:50:42'),
(15, 7, 150.00, '2025-03-05 15:56:46'),
(16, 7, 100.00, '2025-03-05 16:00:13'),
(17, 7, 50.00, '2025-03-05 16:03:22'),
(18, 7, 450.00, '2025-03-05 16:13:41'),
(19, 7, 50.00, '2025-03-05 16:16:57'),
(20, 7, 200.00, '2025-03-05 16:47:42'),
(21, 7, 250.00, '2025-03-06 09:28:54'),
(22, 7, 200.00, '2025-03-06 10:22:42'),
(23, 7, 6.00, '2025-03-06 11:28:36'),
(24, 7, 8.40, '2025-03-06 11:37:44'),
(25, 7, 3.20, '2025-03-06 11:44:19');

-- 
-- Dumping data for table products
--
INSERT INTO products VALUES
(3, 'Vshape Protein', 'Whey protein ', 100.00, 173, '2025-03-05 10:44:47'),
(5, 'Creatine', 'Vshape Creatine', 50.00, 90, '2025-03-05 13:39:04'),
(6, '5904233620163', 'Cotex Tissue Box', 2.00, 9993, '2025-03-06 11:15:27'),
(7, '9501101373655', 'Bactigel Handgel', 1.20, 997, '2025-03-06 11:37:07');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(7, 'henry@gmail.com', 'ali', '$2y$10$vC41AOMLc.nfBlZFOwukkuN/44tpQIlIjnGdRMMOVdlzOTf5fT5zq', '754bcf4b23f6b6f887e30182f22ac0b7bd577256d26e7e744546ac8403ee855a3aa236909dd98571731913e85f8dd1b1e7c9', '2020-09-24 17:53:37', 1, 1, 1, 1, NULL),
(11, 'ali@gmail.com', 'alioss', '$2y$10$83pATx.M9lbHYJl7eMgUROFpFh8iT78cXvchFAOwm8j0ky0ypijAC', 'e3f8fe5f5d6236dce4dbce6aed0586d37b803d33da855047a06154a82f27bcdf98137d74a414adf3aa660fa6c33f010be0fa', '2024-11-25 10:39:58', 0, 1, 1, 1, '+961 76313174'),
(12, 'test@email.com', 'alijamil', '$2y$10$JZ1Qg.jWSD.xPjfhF5diA.R0lvArJ5eVwyBGFkOcADl86jgVPFN1i', '83e0c5819c815e507c0690ef07b8fdccc412a5a7eb2abfbdb8123b6adc252649ad4ff05f9cb67fb150834088190a5128273f', '2024-12-30 11:21:20', 0, 1, 1, 1, NULL),
(13, 'testtest@test.test', 'test', '$2y$10$/NWzf5L6SzQZ8lyn/d8B8OLe0XuBagvnNYw4Jziyf2eu4dMNnTWt2', '35448c560e5a1a12d9708c2fb25d31cd30c8cf7d92cd6df5e3f3f8785bff85eec602abac6f08f81ff3ba6fc3fd674c2ef4b0', '2025-01-07 13:44:01', 0, 1, 1, 1, NULL),
(14, 'customer.service@webmail-cd.com', 'zeina', '$2y$10$kttt1sAls4t0D86krcMhouJGFvBRVmfs2vZbQEQ0d3.Hdhgvarh8K', 'ea950df6934355aff819c59e2374887010b7f15a88133995fb3cadf229846095e6b3577338fbf1bf452b419142be1b02f5de', '2025-02-04 08:20:55', 0, 1, 1, 1, '+243 904444111'),
(15, 'import2@webmail-cd.com', 'Fatima', '$2y$10$Y2G8DNDACvCmLYz1NH6H1OP5Por5K0i7lSVj.QKPKDWDqTKiyr8k6', '7a152f4f336b13bd1b0c179796f7ca953bbe501a9264b09d6f99fd2c53229b8d354bb2b9d00514316b323218cf2ef3eceb0a', '2025-02-04 08:23:09', 0, 1, 1, 1, '+243 900232323'),
(16, 'import6@webmail-cd.com', 'rayane', '$2y$10$WM9CaEYbIBuZy1Syv.9kfu13l6Oz8MgNL20l7ipsjDKB2cPk9bN9G', 'f9249ab27dddc56a251b3d2147a30e287cf23a573078b65a0fac9464d25b2f6c1ce60c6510d597943b0455cc8540522915cf', '2025-02-04 08:23:56', 0, 1, 1, 1, '+243 811023076'),
(17, 'import@webmail-cd.com', 'Zaynab', '$2y$10$SHxh441kI1J5qGGku416R.ZZxTmIevN0VQO2YpTAyeg2Uzs943nou', '9ecafb8091f069bebe85f23fdf13a1af57500807b864d141bff030f2773ddec4b2deb608cf82c3fd6232577655dc35e13f82', '2025-02-04 08:24:52', 0, 1, 1, 1, '+243 828300586'),
(18, 'import4@webmail-cd.com', 'Sleiman', '$2y$10$QvQAqNTRnCH5FpeaI8rHGu5BNnq6yxutPkAQMr0XbipE4X1KtMZ5u', '57049f9005aab867851955f922888d5f0599019e2429aa074cef97701a2242eff68759bc572eae9086be8836719d863621fd', '2025-02-04 08:26:01', 0, 1, 1, 1, '+243 832135341'),
(19, 'import7@webmail-cd.com', 'Anjie', '$2y$10$0hWum/Fk2fm.y2Em2mfqO.vF30ASKlmaBRQwe0meqyoK2XQKevs7W', 'fcc16e0aee0204846ee6ccaba3d23dd3674baabf41a68a9244a26246093847990048848171cf62e42c117fc5f62cfaa146ac', '2025-02-04 08:27:16', 0, 1, 1, 1, '+243 900033888'),
(20, 'frankbula8@gmail.com', 'frank', '$2y$10$dIcFk/fT5gp8OLugaGQoI.EUPr7Yk4Gl7l/2iO7EqF0iS0/YblX6C', 'c91017dbef3361f7d72fdedf2fc01910656577a5de56906700baf11e06294faa6c7cec142c48d28fefd6240612b65106374f', '2025-02-04 08:27:49', 0, 1, 1, 1, '+243 904074200'),
(21, 'logistic@chemaf.net', 'ibrahim', '$2y$10$J//sTS.UvfVkVwm6Sxmly.3Rglxf3PIDiPQQTCJdqCJddve5vYLQG', 'bcd6af01f579b8c5a05898db35b0b33cfd34da9f1d25d22f36a34e87e3d565f639cb666597112e84f1aeee9d7a28c26a8dad', '2025-02-04 13:19:19', 0, 1, 1, 1, '+243 903537750'),
(22, 'afrifood@webmail-cd.com', 'Hoteit', '$2y$10$kYmo0qdP9mqZVpulQkfaNuQ8YJrS8VYeUcK1QC2Aw0YNB5s.Ak7Eq', '2b82306f4477b63a97e6b43eea16339fc7ce66933b601363a65b5964ea49d5281e4fdb0160462d31f160d239e73409258d32', '2025-02-11 14:41:19', 0, 1, 1, 1, '+243 831 470 744');

-- 
-- Dumping data for table sale_items
--
INSERT INTO sale_items VALUES
(1, 1, 3, 2, 100.00),
(2, 2, 3, 1, 100.00),
(3, 3, 3, 0, 100.00),
(4, 5, 3, 0, 100.00),
(5, 5, 5, 0, 50.00),
(6, 6, 3, 3, 100.00),
(7, 7, 3, 3, 100.00),
(8, 7, 5, 1, 50.00),
(9, 8, 5, 2, 50.00),
(10, 8, 3, 4, 100.00),
(11, 9, 5, 11, 50.00),
(12, 10, 5, 100, 50.00),
(13, 11, 5, 1, 50.00),
(14, 11, 3, 2, 100.00),
(15, 12, 3, 1, 100.00),
(16, 13, 5, 99, 50.00),
(17, 14, 5, 3, 50.00),
(18, 15, 5, 1, 50.00),
(19, 15, 3, 1, 100.00),
(20, 16, 3, 1, 100.00),
(21, 17, 5, 1, 50.00),
(22, 18, 5, 1, 50.00),
(23, 18, 3, 4, 100.00),
(24, 19, 5, 1, 50.00),
(25, 20, 5, 2, 50.00),
(26, 20, 3, 1, 100.00),
(27, 21, 5, 1, 50.00),
(28, 21, 3, 2, 100.00),
(29, 22, 3, 2, 100.00),
(30, 23, 6, 3, 2.00),
(31, 24, 7, 2, 1.20),
(32, 24, 6, 3, 2.00),
(33, 25, 6, 1, 2.00),
(34, 25, 7, 1, 1.20);

-- 
-- Dumping data for table payments
--
INSERT INTO payments VALUES
('67c5d00c164dc', '0', 150.00, 'cash', '2025-03-03 16:51:40', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6a63fc145a', '0', 150.00, 'cash', '2025-03-04 08:05:35', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6baadafcb4', '0', 150.00, 'cash', '2025-03-04 09:32:45', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6bf3df3925', '0', 150.00, 'cash', '2025-03-04 09:52:14', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6bfe97d779', '0', 150.00, 'cash', '2025-03-04 09:55:05', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6c13294296', '0', 150.00, 'cash', '2025-03-04 10:00:34', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6c3644fa60', '6e013dacafecbf8c4a0f57bef2ab6f87', 150.00, 'cash', '2025-03-04 10:09:56', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6c40d1dfe6', 'b46650b6f25f70010602a2f3939726e3', 150.00, 'cash', '2025-03-04 10:12:45', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6cf1e1cb87', '1', 150.00, 'cash', '2025-03-04 10:59:58', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6d04c6c2e7', 'ff1e89f3dd169e3a57040903c51ea385', 150.00, 'cash', '2025-03-04 11:05:00', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6d7137b2a9', 'b46650b6f25f70010602a2f3939726e3', 150.00, 'cash', '2025-03-04 11:33:55', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6ebc2eed7a', 'd1bdfef96381437ae629f7aae009fc2a', 150.00, 'cash', '2025-03-04 13:02:10', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c6ebe748c9d', 'ff1e89f3dd169e3a57040903c51ea385', 150.00, 'cash', '2025-03-04 13:02:47', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c71a54d0da7', 'b255f43f4b6281fc381870d88487951d', 150.00, 'cash', '2025-03-04 16:20:52', 'Completed', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c7fa7c5815b', 'b255f43f4b6281fc381870d88487951d', 150.00, 'cash', '2025-03-05 08:17:16', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c7fab933c20', 'b46650b6f25f70010602a2f3939726e3', 150.00, 'cash', '2025-03-05 08:18:17', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c7fac3d7456', 'ff1e89f3dd169e3a57040903c51ea385', 150.00, 'cash', '2025-03-05 08:18:27', 'Pending', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('67c7ffd3142e1', '81d29b8bba190529928c5166e441efad', 500.00, 'cash', '2025-03-05 08:40:03', 'Completed', '4ba8ee26-f990-11ef-9dcc-cc28aa53b74d');

-- 
-- Dumping data for table packages
--
INSERT INTO packages VALUES
('ee6fae48-f842-11ef-aeee-cc28aa53b74d', 'Starter Package', 150.00, 30),
('4ba8ee26-f990-11ef-9dcc-cc28aa53b74d', 'Yearly Plan', 2000.00, 365);

-- 
-- Dumping data for table inventory_transactions
--
-- Table gms.inventory_transactions does not contain any data (it is empty)

-- 
-- Dumping data for table clients
--
INSERT INTO clients VALUES
('1', 'Ali Osseili', '+961 76 313174', 'active', '2025-06-04', '2025-03-03 08:56:47', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('81d29b8bba190529928c5166e441efad', 'John Doe', '3254361', 'active', '2026-03-06', '2025-03-05 08:40:03', '4ba8ee26-f990-11ef-9dcc-cc28aa53b74d'),
('b46650b6f25f70010602a2f3939726e3', 'Client 6', '68735148', 'active', '2025-05-03', '2025-03-04 10:12:45', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('d1bdfef96381437ae629f7aae009fc2a', 'xdfxdf', '45485', 'inactive', NULL, '2025-03-04 13:02:10', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d'),
('ff1e89f3dd169e3a57040903c51ea385', 'Client 7', '98463516', 'active', '2025-05-03', '2025-03-04 11:05:00', 'ee6fae48-f842-11ef-aeee-cc28aa53b74d');

-- 
-- Dumping data for table alert_log
--
INSERT INTO alert_log VALUES
(2, '2025-03-03', '2025-03-03 11:29:01'),
(3, '2025-03-04', '2025-03-04 08:04:38'),
(4, '2025-03-05', '2025-03-05 08:07:30'),
(5, '2025-03-06', '2025-03-06 09:10:34');

--
-- Set default database
--
USE gms;

--
-- Drop trigger `after_payment_completed`
--
DROP TRIGGER IF EXISTS after_payment_completed;

--
-- Drop trigger `before_insert_packages`
--
DROP TRIGGER IF EXISTS before_insert_packages;

--
-- Set default database
--
USE gms;

DELIMITER $$

--
-- Create trigger `before_insert_packages`
--
CREATE
DEFINER = 'root'@'localhost'
TRIGGER before_insert_packages
BEFORE INSERT
ON packages
FOR EACH ROW
BEGIN
  -- Generate a new UUID and set it as the 'id' of the new row
  SET NEW.id = UUID();
END
$$

--
-- Create trigger `after_payment_completed`
--
CREATE
DEFINER = 'root'@'localhost'
TRIGGER after_payment_completed
AFTER UPDATE
ON payments
FOR EACH ROW
BEGIN
  -- Declare the necessary variables
  DECLARE num_days int;
  DECLARE current_subscription_end_date date;

  -- Check if payment_status is changing from 'pending' to 'completed'
  IF OLD.payment_status = 'pending'
    AND NEW.payment_status = 'completed' THEN
    -- Get the number_of_days from the packages table based on package_id
    SELECT
      number_of_days INTO num_days
    FROM packages
    WHERE id = NEW.package_id
    LIMIT 1;  -- Ensure only one row is returned

    -- Get the current subscription_end_date of the client
    SELECT
      subscription_end_date INTO current_subscription_end_date
    FROM clients
    WHERE client_id = NEW.client_id
    LIMIT 1;  -- Ensure only one row is returned

    -- Update the client subscription_status to 'active'
    UPDATE clients
    SET subscription_status = 'active'
    WHERE client_id = NEW.client_id;

    -- If subscription_end_date is NULL, set it to today's date + num_days
    IF current_subscription_end_date IS NULL THEN
      UPDATE clients
      SET subscription_end_date = CURDATE() + INTERVAL num_days DAY
      WHERE client_id = NEW.client_id;
    ELSE
      -- If subscription_end_date is not NULL, add num_days to the existing subscription_end_date
      UPDATE clients
      SET subscription_end_date = DATE_ADD(current_subscription_end_date, INTERVAL num_days DAY)
      WHERE client_id = NEW.client_id;
    END IF;
  END IF;
END
$$

DELIMITER ;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;